[WIP] Support rootURL.
ember-engines/ember-asset-loader pull request #33
Opened 2016-11-01 20:26 UTC by nathanhammond

Supersedes #32. Closes #29.

- [ ] Tests.

2016-11-02 03:20 UTC, trentmwillis requested changes
Seems good on first pass. We should try to breakdown the `postprocessTree` function if possible.

2016-11-02 03:20 UTC, trentmwillis commented on lib/asset-manifest-generator.js
> +      // `prepend` should be normalized to have a leading and trailing `/`.
I feel like these two line comments should be moved inside the `if` below.

2016-11-02 03:20 UTC, trentmwillis commented on lib/manifest-generator.js
> +    var appBuildtimeOptions = app && app.options && app.options.assetLoader;
Can we name this `assetLoaderOptions`, like we have it below?

2016-11-02 03:20 UTC, trentmwillis commented on lib/manifest-generator.js
> +    // Also checks `baseURL` to support the old `baseURL` setting.
Is this really worth supporting? It's old, this addon is new, I'd prefer not supporting it.

2016-11-02 04:35 UTC, nathanhammond commented on lib/manifest-generator.js
> +    // Also checks `baseURL` to support the old `baseURL` setting.
In Ember CLI 2.6 we used `baseURL` and 2.7 we added `rootURL` and deprecated (but still support) `baseURL`-only setups. It's not old enough in my opinion to drop the branching support.

2016-11-02 04:58 UTC, nathanhammond commented on lib/asset-manifest-generator.js
> +      // `prepend` should be normalized to have a leading and trailing `/`.
Expanded upon them for future travelers.

2016-11-02 04:58 UTC, nathanhammond commented on lib/manifest-generator.js
> +    var appBuildtimeOptions = app && app.options && app.options.assetLoader;
☑️

2016-11-06 01:49 UTC, trentmwillis commented
I think we could probably move the logic for constructing the `manifestOptions` into a separate function. I think that will fix the code climate check and keep the complexity low.

2017-04-13 20:10 UTC, trentmwillis commented
Closing this as I believe we wound up not wanting to take this approach (and it has gone stale).

2017-04-13 20:10 UTC, closed without merging