Sets async to false when loading scripts.
ember-engines/ember-asset-loader pull request #38
Opened 2016-11-28 05:19 UTC by MiguelMadero

This helps us guarantee the order as [specified on the RFC](https://github.com/emberjs/rfcs/pull/153/files#diff-36ac857d583c44e56b932989bf30f8daR37). If the attribute isn't specified the behavior accross browsers is inconsistent, Gecko for example won't enforce execution order. Non-supporting browsers (e.g. IE9) still execut asynchronously.

On a large project, we had about a 1 error every 10,000  loads due to execution order. It didn't happen for the first 3 months that we had lazy-loading, until we added some other parts of the app with stronger dependencies in load order. Mostly AMD modules were fine, but we had some code that dependend on vendor assets that relied on globals.

Extract from https://developer.mozilla.org/en/docs/Web/HTML/Element/script

> [1] In older browsers that don't support the async attribute, parser-inserted scripts block the parser; script-inserted scripts execute asynchronously in IE and WebKit, but synchronously in Opera and pre-4.0 Firefox. In Firefox 4.0, the async DOM property defaults to true for script-created scripts, so the default behavior matches the behavior of IE and WebKit. To request script-inserted external scripts be executed in the insertion order in browsers where the document.createElement("script").async evaluates to true (such as Firefox 4.0), set .async=false on the scripts you want to maintain order. Never call document.write() from an async script. In Gecko 1.9.2, calling document.write() has an unpredictable effect. In Gecko 2.0, calling document.write() from an async script has no effect (other than printing a warning to the error console).
> [2] Starting in Gecko 2.0 (Firefox 4 / Thunderbird 3.3 / SeaMonkey 2.1), inserting script elements that have been created by calling document.createElement("script") into the DOM no longer enforces execution in insertion order. This change lets Gecko properly abide by the HTML5 specification. To make script-inserted external scripts execute in their insertion order, set .async=false on them.

2016-11-28 17:36 UTC, trentmwillis commented
This seems good to me. Can we update the tests to verify that `async` is properly set when the script is inserted?

2016-11-30 00:55 UTC, MiguelMadero commented
done

2016-11-30 02:36 UTC, trentmwillis requested changes
One super small thing and then this should be good to go!

2016-11-30 02:36 UTC, trentmwillis commented on tests/unit/services/asset-loader-test.js
> +test('loadAsset() - js - sets async false to try to gurantee execution order', function(assert) {
Typo: `gurantee` -> `guarantee`

2016-11-30 17:39 UTC, trentmwillis approved these changes

2016-11-30 17:39 UTC, merged

2016-11-30 17:39 UTC, trentmwillis commented
Thanks!

2016-11-30 17:50 UTC, trentmwillis commented
Released in `v0.2.6`

2017-05-24 16:37 UTC, stefanpenner commented
We may want to revisit this, allowing non-vendor bundles containing only AMD to opt-out.

cc @scalvert

2017-05-24 18:30 UTC, trentmwillis commented
Note that you can also provide your own, custom loading function via [`defineLoader`](https://github.com/ember-engines/ember-asset-loader/blob/55c93d036d84855ae9a75d9a904656c7cfaed933/addon/services/asset-loader.js#L141-L152) if you want to experiment with things.