Add README details about re: broccoli-asset-rev
ember-engines/ember-asset-loader pull request #44
Opened 2017-01-29 23:56 UTC by lukemelia

Added a section about working with broccoli-asset-rev and some other clarifications to make things clearer that confused me.

2017-01-31 00:16 UTC, trentmwillis requested changes
Thanks for putting this together!

A few smallish changes I'd like to see, but overall this is looking solid.

2017-01-31 00:16 UTC, trentmwillis commented on README.md
> +placed into the asset manifest. This defaults to `bundles`. Each bundle is a directory containing files that will be be downloaded when the bundle is requested. You are responsible for getting the ri
Repeated word: `be be`.

2017-01-31 00:16 UTC, trentmwillis commented on README.md
> +This addon doesn't perform manifest generator just by virtue of being installed because there is no convention for
Small grammar thing: `generator` should be `generation`

2017-01-31 00:16 UTC, trentmwillis commented on README.md
> +### Using With `broccoli-asset-rev`
I'm unsure we need an example this long. I think we simply need to mention that `broccoli-asset-rev` needs to run after your addon and that you can specify that via the `ember-addon.after` field in the `package.json`.

I want to make sure the readme doesn't become overly verbose (makes it harder to locate things quickly). If you feel this much detail is definitely needed, maybe we could start up a wiki or additional docs folder.

2017-03-15 14:42 UTC, lukemelia commented on README.md
> +### Using With `broccoli-asset-rev`
Given that `broccoli-asset-rev` ships with ember-cli apps by default, I feel strongly that this belongs in the README in step-by-step fashion unless we can make the steps unnecessary. This was the biggest stumbling block for me in trying to adopt this addon after seeing your talk.

2017-03-15 14:42 UTC, lukemelia commented
I'm sorry this sat for so long -- I missed the notification of your review @trentmwillis and just saw it while returning to the github repo for another reason.

2017-03-24 01:20 UTC, trentmwillis commented on README.md
> +### Using With `broccoli-asset-rev`
Okay, seems fine then. I'm not super against and as someone who is super close to the project, I am likely less attuned to what the readers need.

2017-03-24 01:22 UTC, trentmwillis approved these changes

2017-03-24 01:22 UTC, merged