feat: use travis stages to run tests with and without a lockfile
ember-engines/ember-asset-loader pull request #68
Opened 2018-03-19 17:41 UTC by lennyburdette

2018-03-19 18:14 UTC, rwjblue requested changes
Looks really nice, made a few inline comments but I'd love to move forward...

2018-03-19 18:14 UTC, rwjblue commented on .travis.yml
> +    - env: NAME=test # used only to make Travis UI show description
Lets have this be the main `test` stage, and then make the other things be `additional tests` stage (no need to run them if we don't have non-floating chrome only tests passing)...

2018-03-19 18:14 UTC, rwjblue commented on .travis.yml
> +    - env: NAME=floating dependencies sauce
we can probably remove this one (I think checking floating deps with chrome only is probably enough)

2018-03-19 19:51 UTC, lennyburdette commented
I had to regenerate the lockfile since our private registry had cached something that's been yanked from npmjs.org. Looks like it works now tho!

2018-03-19 20:07 UTC, rwjblue reviewed
Sorry for the run around @lennyburdette, I think one last tweak and we are good to go!

2018-03-19 20:07 UTC, rwjblue commented on .travis.yml
> +    - env: NAME=test sauce
Lets move this one into additional tests too.

Basically, I want a single job that runs in the first stage which is using the lockfile (e.g. no drift), then do the other two things in "additional tests"...

2018-03-19 22:14 UTC, lennyburdette commented
@rwjblue no worries, I should've read your previous comment more closely. All good now!

2018-03-20 00:58 UTC, rwjblue approved these changes

2018-03-20 00:58 UTC, merged

2018-03-20 01:01 UTC, rwjblue commented
Awesome work here, thank you! I really like this pattern (it makes it clear where a particular type of failure comes from, avoids wasting CI time, etc). Hopefully we can leverage the same thing in the addon blueprint to bring the awesomeness to all addons automatically....